Feature/attributes
campudus/tableaux pull request #238
Opened 2021-09-29 19:05 UTC by CoffeeGinger

- [x ] I gave the PR a meaningful name
- [ x] I checked that the correct target branch is selected
- [ x] I rebased the branch on the target branch and it can be merged
- [ ] I ran the linter and it did pass
- [ x] I checked for unused code / dead code / debug code
- [ x] I checked that variables/functions have meaningful names
- [x ] I checked that the behaviour is as the documentation/task describes and I tested it
- [x ] I updated the docs / specifications if possible
- [ x] I could explain all that code when someone wakes me up at 3am
- [x ] I checked that the code considers failures and not just the happy path
- [x ] There are no new dependencies OR I listed them and explained them below
- [x ] PR introduces no breaking changes OR I listed them and described them below
- [ x] I added/updated tests for new/modified unit-testable functions/helpers
- [ ] I ran the tests and they did pass

## Other information/comments (e.g. reasons why points are not checked from above)
-linter: Haben wir in dem Projekt überhaupt einen? Falls ja, lasse ich den nach dem Review laufen
- Zwei GroupColumnTests funktionieren nicht, was allerdings nichts mit den Änderungen zu tun haben dürfte, das schaue ich mir jetzt dann noch während des Reviews an
## Reason for this PR
- Es wurden generische Attribute für Tables und Columns implementiert, spezifiziert in: https://app.activecollab.com/116706/projects/2?modal=Task-26920-2

2021-09-30 14:23 UTC, Zwergal requested changes
I'm also missing some new tests which explicitly test adding column or table attributes (Positive tests) and also tests where wrong data like numbers etc. are inserted and the Exception is thrown.

2021-09-30 14:23 UTC, Zwergal commented on src/main/scala/com/campudus/tableaux/database/model/structure/ColumnModel.scala
> +          val attributes = createColumn.attributes.map(atts => atts.encode()).getOrElse("{}")
[minor] Wrong indentation

2021-09-30 14:23 UTC, Zwergal commented on src/main/scala/com/campudus/tableaux/database/model/structure/TableModel.scala
> +                     )
[Minor] Wrong indentation. I would suggest to place both brackets in one line like `})`

2021-09-30 14:23 UTC, Zwergal commented on src/main/scala/com/campudus/tableaux/helper/JsonUtils.scala
> +import com.campudus.tableaux.{InvalidJsonException,WrongJsonTypeException, TableauxConfig}
[Minor] Missing space between `InvalidJsonException,` and `WrongJsonTypeException`

2021-09-30 14:23 UTC, Zwergal commented on src/main/scala/com/campudus/tableaux/helper/JsonUtils.scala
> +          }
[Minor] Wrong indentation

2021-09-30 14:23 UTC, Zwergal commented on src/main/scala/com/campudus/tableaux/helper/JsonUtils.scala
> +          }
[Minor] Wrong indentation

2021-09-30 14:23 UTC, Zwergal commented on src/main/scala/com/campudus/tableaux/router/StructureRouter.scala
> +import com.campudus.tableaux.{InvalidJsonException,WrongJsonTypeException, TableauxConfig}
[Minor] Missing space between `InvalidJsonException,` and  `WrongJsonTypeException`

2021-09-30 14:23 UTC, Zwergal commented on src/main/scala/com/campudus/tableaux/router/StructureRouter.scala
> +          }
[Minor] Wrong indentation

2021-10-07 09:17 UTC, Zwergal commented
> > ## Other information/comments (e.g. reasons why points are not checked from above)
> > -linter: Haben wir in dem Projekt überhaupt einen? Falls ja, lasse ich den nach dem Review laufen
> 
> Ja, wir nutzen scalafmt über spotless. Wenn ich mich recht erinnere, sollte `gradlew spotless` auch fixen und nicht nur Fehler werfen. Findet man auch in der `build.gradle`. Eigentlich sollte das auch ein check hier im PR sein. Aber scheinbar fehlen die travis-ci checks auch komplett... Vll. passt da was nicht mehr, weil travis-ci.org nun zu travis-ci.com umgezogen ist. Das Projekt ist insgesammt etwas angestaubt. Müsste man sich auch mal alles anschaun.
> 
> > ```
> > * Zwei GroupColumnTests funktionieren nicht, was allerdings nichts mit den Änderungen zu tun haben dürfte, das schaue ich mir jetzt dann noch während des Reviews an
> > ```
> 
> Zu den failenden Tests sieht man hier auch nichts. Sehr grad auf dem Jenkins failen die Test ja auch seit Anfang August. Travis letzter und zugleich erfolgreicher build war am 25.02.2021 -> https://app.travis-ci.com/github/campudus/tableaux

Travis und Jenkins sind beide gefixed und bauen wieder richtig. `gradlew spotlessApply` muss noch ausgeführt werden, damit die Format-Fehler weg sind @s-tschne

2021-12-08 08:00 UTC, Zwergal requested changes

2021-12-09 09:14 UTC, CoffeeGinger commented on src/main/scala/com/campudus/tableaux/router/StructureRouter.scala
> +        }
![image](https://user-images.githubusercontent.com/40287903/145367620-6d385d74-9ec7-4773-b6a1-4dae1084fe22.png)
Die Funktion getJsonObject gibt, wenn der key nicht existiert null zurück. Ist das der Fall, wird einfach nichts in die Datenbank geschrieben.

2021-12-09 09:20 UTC, CoffeeGinger commented on build.gradle
> +  maven { url 'https://jitpack.io' }
Auf jitpack liegt  der Json Schema Validator ,"com.github.everit-org:json-schema:1.14.0"

2021-12-10 13:07 UTC, zingmane commented on build.gradle
> +  maven { url 'https://jitpack.io' }
Grundsätzlich würde ich auch eher alles aus einer Quelle holen wollen.
https://github.com/everit-org/json-schema/issues/427
Der Maintainer veröffentlicht das selbe package auch unter https://mvnrepository.com/artifact/com.github.erosb/everit-json-schema

2021-12-16 16:27 UTC, Zwergal commented on src/main/scala/com/campudus/tableaux/router/StructureRouter.scala
> +        }
Ok, aber warum musste dann in alle vorhandenen Tests in die Requests ein leers Json-Objekt reingepackt werden? Das könnte man ja weglassen.

2021-12-17 08:51 UTC, Zwergal requested changes

2021-12-17 08:51 UTC, Zwergal commented on src/main/scala/com/campudus/tableaux/helper/FileUtils.scala
> +  def readSchemaFromFS(indexJson: JsonArray): Future[List[JsonObject]] = {
Kann diese Funktion auch private sein? Wird ja nur unten von `getSchemaList` genutzt, oder?

2021-12-17 08:51 UTC, Zwergal commented on src/test/scala/com/campudus/tableaux/api/structure/CreateColumnTest.scala
> +                 "attributes" -> Json.obj(),
Warum muss bei den vorhandenen Tests immer ein leeres JSON Objekt mitgegeben werden? Das ist doch optional, oder?

2021-12-21 18:37 UTC, CoffeeGinger commented on src/test/scala/com/campudus/tableaux/api/structure/CreateColumnTest.scala
> +                 "attributes" -> Json.obj(),
Ja, macht vmtl keinen Sinn das überall rein zu tun. Nehm ich wieder raus, könnte verwirrend sein.

2022-01-11 14:40 UTC, zingmane reviewed
Hab jetzt endlich auch mal Zeit gefunden mir den PR anzusehn. Bis auf die Anmerkungen sieht es von meiner Seite gut aus. 👍

2022-01-11 14:40 UTC, zingmane commented on src/test/scala/com/campudus/tableaux/api/structure/ColumnAttributesTest.scala
> +        Json.obj("columns" -> Json.arr(Json.obj("kind" -> "text", "name" -> "column1", "attributes" -> attributes)))
**[suggestion]** - Hm, ich glaub es macht wenig Sinn, die columns mit den selben attributes up-zu-daten wie sie erzeugt wurden. Der Test wäre auch iO, wenn das update ins leere laufen würde. Am besten wäre denke ich, die columns ohne attributes zu erzeugen.

2022-01-11 14:40 UTC, zingmane commented on src/test/scala/com/campudus/tableaux/api/structure/ColumnAttributesTest.scala
> +        test2 <- sendRequest("POST", "/tables/1/columns", createColumn2)
**[suggestion]** - Bei einigen Tests hat der zweite req irgendwie keinen Mehrwert. Bin nicht 100% sicher, was an der Stelle passiert, glaube allerdings, dass der erste request schon für den assert true ausreicht und der zweite garnicht mehr ausgeführt wird. Aus meiner Sicht, kann der zweite deshalb weg.

Das gleiche gilt für die weiteren Test. 👇

2022-01-13 07:16 UTC, Zwergal approved these changes
Von meiner Seite ist nichts mehr offen. Nur Manes Anmerkungen noch, dann sollte es passen.
.

2022-01-25 14:08 UTC, zingmane approved these changes
lgtm

2022-01-25 14:22 UTC, merged