Add endpoint to query single cell's annotations
campudus/tableaux pull request #244
Opened 2022-03-14 13:46 UTC by hermann-p

`GET /tables/:tableID/columns/:columnID/rows/:rowID/annotations` -> {"annotations": CellLevelAnnotations }

2022-03-14 14:56 UTC, Zwergal requested changes

2022-03-14 14:56 UTC, Zwergal commented on src/main/scala/com/campudus/tableaux/database/model/TableauxModel.scala
> +      (_, cellLevelAnnotations) <- retrieveRowModel.retrieveAnnotations(column.table.id, rowId, Seq(column))
`retrieveAnnotations` liefert ja zusätzlich zu den Zellannotations auch eine evtl. rowAnnotation, oder? Das wäre ja eigentlich zu viel. Wir hatten gesagt, wir wollen hier nur die Zellannotations und nicht die der row.

2022-03-14 14:56 UTC, Zwergal commented on src/test/scala/com/campudus/tableaux/api/content/CellLevelAnnotationsTest.scala
> +  @Test
Ich vermisse noch einen Test mit einer Zelle bei der die Zeile eine Annotation hat. Diese Zeilenannotation sollte dann nicht mit ausgeliefert werden, wenn man die Zellannotations abruft.

Wäre zudem evtl. noch ein Test mit mehr als einer Annotation sinnvoll, dass man prüft, dass auch die richtige Anzahl zurückkommt?

2022-03-17 07:18 UTC, hermann-p commented on src/main/scala/com/campudus/tableaux/database/model/TableauxModel.scala
> +      (_, cellLevelAnnotations) <- retrieveRowModel.retrieveAnnotations(column.table.id, rowId, Seq(column))
Der Wert ist ein Tupel, aus Row-Annotation und Cell-Annotation; der erste  Teil (die Row-Annotationen) wird hier schön sichtbar verworfen (`_`) :)

2022-03-17 07:18 UTC, hermann-p commented on src/test/scala/com/campudus/tableaux/api/content/CellLevelAnnotationsTest.scala
> +  @Test
Können wir noch machen, klar.

2022-03-17 09:08 UTC, Zwergal approved these changes

2022-03-17 09:11 UTC, merged