Feature/messaging
campudus/tableaux pull request #262
Opened 2022-11-02 20:31 UTC by CoffeeGinger

Implements a Messaging/Webhook Verticle.

2022-11-03 09:22 UTC, hermann-p reviewed
Schaut nachvollziehbar aus.
Mich stört ein wenig, dass in allen beteiligten Funktionsbodys in jeden möglichen Ausgangszweig explizit ein weiterer Effekt eingebaut werden muss; das finde ich unsauber und fehleranfällig. 
Leider nimmt uns das Gedöns mit den impliziten Variablen viele Möglichkeiten, das sauber zu refaktorisieren.

2022-11-09 14:28 UTC, CoffeeGinger commented
Fehlende tests wurden hinzugefügt.

2022-11-21 17:50 UTC, zingmane reviewed
Sieht erst mal gut aus. Die Sache mit dem Service hat mich erst mal etwas verwirrt, weil ich dachte dass man sich da auch von außen ganz normal registrieren kann. Wenn ich es richtig verstehe, dann ist das aber nur um intern die listener neu zu laden. 

Vll. wärs dann besser einen ganz anderen Namen zu verwenden, damit das klarer wird. Vll. brauchts das aber auch nicht. Vll. gehts nur mir so damit, mal schaun.

Ich würde es die nächsten Tage noch manuell.

2022-11-21 17:50 UTC, zingmane commented on project/build.properties
> +sbt.version=1.7.1
Für was brauchen wir das? Zu bauen nutzen wir gradle und nicht sbt

2022-11-21 17:50 UTC, zingmane commented on src/main/scala/com/campudus/tableaux/verticles/MessagingVerticle/MessagingVerticleClient.scala
> +    sendMessage(MessagingVerticle.ADDRESS_SERVICES_CHANGE)
Damits einheitlich sollte das stett `ADDRESS_SERVICES_CHANGE` besser `ADDRESS_SERVICE_CHANGED` heißen.

2022-11-21 17:50 UTC, zingmane commented on src/main/scala/com/campudus/tableaux/router/SystemRouter.scala
> +          messagingClient.servicesChange()
Wollten wir das bei den services global machen, weil es eh nie viele sein werden oder?
Dann passt der Plural, aber besser wäre dann hier auch einheitlich die Vergangenheit zu nutzen, also `changed`.

2022-11-21 17:50 UTC, zingmane commented on src/main/scala/com/campudus/tableaux/verticles/MessagingVerticle/MessagingVerticle.scala
> +    eventBus.consumer(ADDRESS_SERVICES_CHANGE, messageHandlerUpdateListeners).completionFuture()
Ach jetzt versteh ichs glaube ich, der listener/handler für services wird nur intern verwendet, damit die configs neu geladen werden können, richtig?

2022-11-22 09:13 UTC, zingmane commented on src/test/scala/com/campudus/tableaux/Verticles/MessagingVerticle/MessagingVerticleTest.scala
> +    logger.info("createStrucutreController")
typo in structure

2022-11-22 10:17 UTC, zingmane requested changes

2022-11-22 10:17 UTC, zingmane commented on src/test/scala/com/campudus/tableaux/Verticles/MessagingVerticle/MessagingVerticleTest.scala
> +      "scope" -> "global",
Ist vermutlich ein c&p Relikt, weil für den service type `listener` brauchen wir den type "global" denke ich nicht, zumindest wertest du den nicht aus. Wenn dann müsste es auch `"type": "global"` heißen, aber ich denke das kann ganz weg.

2022-11-22 10:32 UTC, zingmane requested changes
Ich hab jetzt ziemlich viel manuell durchgetestet. 
https://webhook.site/ ist dafür ziemlich cool.

Ich finds generell ziemlich gut, auch die Doku hat geholfen. Nur hab ich die zuerst nicht gefunden. 😁

Die Doku wäre noch anzupassen an die veränderten props, du hast die `includes` und `excludes` noch mal in eigene objects gewrapped.

Ich hatte so meine Probleme mit einer externe url, das hat garnicht funktioniert, vermutlich weil das protocol fehlt. 
Ich habs bei mir lokal im code dann auf `webClient.postAbs(url)` umgestellt, damit hat es auch mit externen URLS gefunzt.

IMHO wäre es vll. eh besser das generell auf einen parameter url umzustellen, würde ja auch für die internen hook funktionieren.
@Zwergal Was meinst du?

2022-11-22 10:34 UTC, zingmane commented on src/main/scala/com/campudus/tableaux/verticles/MessagingVerticle/MessagingVerticle.scala
> +      val headers = config.getJsonObject("headers", Json.obj())
**[major]** -  Headers werden nicht an den requests gepackt

2022-11-22 10:42 UTC, CoffeeGinger commented on src/main/scala/com/campudus/tableaux/verticles/MessagingVerticle/MessagingVerticle.scala
> +    eventBus.consumer(ADDRESS_SERVICES_CHANGE, messageHandlerUpdateListeners).completionFuture()
Genau :)

2022-11-22 14:58 UTC, zingmane commented on src/main/scala/com/campudus/tableaux/verticles/MessagingVerticle/MessagingVerticle.scala
> +  val EVENT_TYPE_CELL_CHANGED = "cell_changed"
Mir ist aufgefallen, dass die events bzw addresses inkonsistent benamt sind. Deshalb hat auch erst mein manueller test nicht funktioniert.
In der doku heißt es z.B. event `cell_change`(Präsens), was ich auch richtig finde. Implementiert ist es aber als `cell_changed` (Präteritum)

Die addresses sind grundsätzlich eher im Präteritum, find ich auch gut. Der value sollte dann aber auch `message.cell.changed` heißen.

2022-11-22 15:01 UTC, zingmane commented
Der listener auf event `cell_change` funktioniert noch nicht in alle fällen. Wenn links in Linkspalten hinzugefügt werden greift er, wenn welche entfernt werden nicht.

https://user-images.githubusercontent.com/148202/203347584-01be7e37-66d5-43a2-98b9-a56503fe364f.mp4

2022-11-22 15:20 UTC, zingmane commented
@hermann-p @s-tschne @Zwergal 
Wie sind wir denn mit folgendem Szenario verblieben?
webhook ist auf bikeModel cell_changed registriert und es ändert sich nicht direkt der Zellwert, sondern ein Wert über eine verlinkte Spalte. Also im krassesten Fall z.B. der Hersteller. 

Aktuell ist es so implementiert, dass man die Änderungen schon mitbekommt, aber nur wenn man sich auf die table manufacturer registriert. Wie hatten wir das final definiert? Ich glaube so, dass auch die cell_change events für die dependent rows rausgeschrieben werden oder?

2024-11-15 10:05 UTC, zingmane reviewed
Ein paar Kleinigkeiten sind für mich noch nicht gelöst, die müssen wir evtl. mal diskutieren.

2024-11-15 11:22 UTC, Zwergal commented
> Hast du das mal getestet? Ich kann mich nicht genau erinnern, aberscheinbar funktioniert es so nur mit internen URLs.
Vll. sollten wir das so erweitern, dass wir entweder immer abolute URLs definieren. Geht halt dann leider für von außen nicht erreichbare services nicht mehr. Oder wir machen uns noch eine optionale config, um auch externe webhook URLs hinterlegen zu können.
> Außerdem müssten wir schaun wie wir die header, wo ja apiKeys etc. drin sein können mit übergeben. Die header werden jetzt einfach nicht berücksichtigt.
@Zwergal Was meinst du? Ich glaube schon, wenn wir das feature einbauen, dass wir auch an externe Services pushen wollen oder?

Ja, das sollte definitiv gehen.
Wir brauchen beide Möglichkeiten. Interne services und auch externe.
Konfigurierbare Header wären schon auch nicht schlecht. Gerade bei sowas wie dem API-Gateway könnte ich mir vorstellen, dass wir einen API-Key oder sowas mitgeben müssten.

2024-12-04 12:03 UTC, zingmane approved these changes

2024-12-04 13:37 UTC, Zwergal approved these changes

2024-12-04 14:21 UTC, merged