Feature/limit text length
campudus/tableaux pull request #265
Opened 2023-01-11 09:00 UTC by CoffeeGinger

AC-Task: https://app.activecollab.com/116706/projects/2?modal=Task-40283-2
This PR implements a minimum and maximum length check of text-based cells.
The minimum and maximum values can be defined as attributes on column level.
For example:
`{
    "columns": [
        {
            "name": "length_check_multilang",
            "multilanguage": true,
            "kind": "text",
            "attributes": {
                "maxLength": {
                    "value": 10,
                    "type": "number"
                },
                "minLength": {
                    "value": 5,
                    "type": "number"
                }
            }
        }
    ]
}`
In this example values [5...10] are permitted, 5 and 10 included, also, zero length is always permitted.

2023-01-13 15:43 UTC, Zwergal requested changes

2023-01-13 15:43 UTC, Zwergal commented on src/main/scala/com/campudus/tableaux/database/model/TableauxModel.scala
> +    val checkMultiLangLength: (Integer => Boolean, JsonObject) => Boolean = (op, multiLangValue) => {
[Minor] Bitte das naming verbessern. Ich denke `op` steht für `operation` oder sowas. Aber das dann auch ausschreiben und keine Abkürzungen verwenden. Macht den code besser verständlich.

2023-01-13 15:43 UTC, Zwergal commented on src/main/scala/com/campudus/tableaux/database/model/TableauxModel.scala
> +      (op, value) => {
[Minor] Bitte das naming verbessern. Ich denke op steht für operation oder sowas. Aber das dann auch ausschreiben und keine Abkürzungen verwenden. Macht den code besser verständlich.

2023-01-13 15:43 UTC, Zwergal commented on src/main/scala/com/campudus/tableaux/database/model/TableauxModel.scala
> +    val checkLength: (Integer => Boolean, Boolean, A) => Boolean = (op, isMultilang, value) => {
[Minor] Bitte das naming verbessern. Ich denke op steht für operation oder sowas. Aber das dann auch ausschreiben und keine Abkürzungen verwenden. Macht den code besser verständlich.

2023-01-13 15:43 UTC, Zwergal commented on src/main/scala/com/campudus/tableaux/database/model/TableauxModel.scala
> +      val asBool = maybeLengthLimits match {
[Minor] `asBool` find ich nicht sehr aussagekräftig als Variablenname. Ich würde hier etwas deutlicheren Namen bevorzugen, an dem man gleich erkennt was dieser boolean bedeutet.
Beispiel: `isValueInRange`

2023-01-13 15:43 UTC, Zwergal commented on src/main/scala/com/campudus/tableaux/exceptions.scala
> +  override val statusCode: Int = 500
[Major] StatusCode 500 steht ja für einen Fehler vom Server. Der Fehler hier kommt aber aus den Input-Parametern. Hier würde der StatusCode 400 "Bad Request" besser passen.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400

> 400 Bad Request response status code indicates that the server cannot or will not process the request due to something that is perceived to be a client error (for example, malformed request syntax, invalid request message framing, or deceptive request routing).

2023-01-13 15:43 UTC, Zwergal commented on src/test/scala/com/campudus/tableaux/api/content/FillCellTest.scala
> +      val expectedCell1 = Json.obj("status" -> "ok", "value" -> "12345")
[Minor] Wird in diesem Test nicht genutzt?

2023-01-13 15:43 UTC, Zwergal commented on src/test/scala/com/campudus/tableaux/api/content/FillCellTest.scala
> +      val expectedCell1 = Json.obj("status" -> "ok", "value" -> "12345")
[Minor] Wird in diesem Test nicht genutzt?

2023-01-18 12:15 UTC, zingmane reviewed
Bis auf die Sachen die Max noch angemerkt hat, sieht es gut aus.
Also Tests laufen noch nicht, da fehlen Argumente beim column create und schema version check wird auch auf 32!=33 laufen.

Bin bissl late to the party, aber:

Generell hab ich mir bei den system_columns mit `min_length` und `max_length` noch gedacht, ob es nicht sinnvoller wäre das in eine column vom Typ jsonb zu werfen. Mag jetzt zu weit vorausgedacht sein, aber vll. kommt in wenigen Wochen/Monaten die Anforderung, dass keine Sonderzeichen im string enthalten sein dürfen oder irgendwelche anderen wearden Sachen, wie validieren, dass ein string eine email ist. 
Dann könnte man diese Definitionen alle in dieser column ablegen, ohne das Schema ändern zu müssen:

```json
{
  "min_length": 5,
  "max_length": 10,
  "can_contain_special_chars": false, // oder
  "regex": "__regex_für_email_der_echte_echte_ist_ziemlich_lange__"
}
```

Auf der anderen Seite können wir das ja wenn wir es brauchen immer noch einführen, müssen dann nur die columns wieder migrieren.

2023-01-23 08:50 UTC, Zwergal requested changes

2023-01-23 08:50 UTC, Zwergal commented on src/main/scala/com/campudus/tableaux/database/model/TableauxModel.scala
> +      (op, value) => {
Hm, das ist noch offen, oder?

2023-02-09 09:13 UTC, zingmane approved these changes
Diese eine Sache von Max ist noch offen, in `src/main/scala/com/campudus/tableaux/database/model/TableauxModel.scala`.
Ansonsten können wir den PR dann bald mal mergen, wenn der länger liegt wird er auch nicht besser.

2023-02-16 22:00 UTC, zingmane approved these changes
lgtm

2023-02-17 08:01 UTC, Zwergal approved these changes

2023-02-17 08:02 UTC, merged